import { Inter } from "next/font/google";
import "./globals.css";
import Transitonpage from "@/components/transition";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sagar's Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Transitonpage>{children}</Transitonpage>
      </body>
    </html>
  );
}
